# -*- coding: utf-8 -*-
"""Speed Breaker & Pothole Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yBXMbWw5gBB27Nf5Af0iJ7b3ZNwkcnQW
"""

!nvidia-smi

!pip install ultralytics

!yolo predict model=yolov8n.pt source='https://ultralytics.com/images/bus.jpg'

# Pip install method (recommended)

!pip install ultralytics==8.0.20

from IPython import display
display.clear_output()

import ultralytics
ultralytics.checks()

from ultralytics import YOLO

from IPython.display import display, Image

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/dataobj

!ls

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/dataobj


!yolo task=detect mode=train model=yolov8s.pt data= data.yaml epochs=25 imgsz=224 plots=True

!ls runs/detect/train4/

Image(filename='runs/detect/train5/confusion_matrix.png', width=600)

Image(filename='runs/detect/train5/val_batch0_pred.jpg', width=600)